dynamically resolves runtime dependencies

diff --git a/sh/crun-node b/sh/crun-node
--- a/sh/crun-node
+++ b/sh/crun-node
@@ -1,9 +1,19 @@
 #!/bin/sh
 set -e
 
-if hash jq 2> /dev/null; then
-  VERSION=$(jq -r '.engines.node' package.json)
-else
-  VERSION=4.1.1
+VERSION_FILE='.cache/node.version'
+if [ 'package.json' -nt "$VERSION_FILE" ]; then
+  mkdir -p '.cache'
+  echo "Resolving node version..."
+  sh/resolve-node-version > $VERSION_FILE
 fi
+
+VERSION=$(cat $VERSION_FILE)
+if [ -z "$VERSION" ]; then
+  echo >&2 "Failed to resolve node version."
+  cat "$VERSION_FILE"
+  rm -f "$VERSION_FILE"
+  exit 1
+fi
+
 ./sh/crun "node:$VERSION" "$@"
